#!/usr/bin/env sh

BUILD="sudo -Eu builder /work/void-packages/xbps-src $BUILD_ARGS -j$(nproc) -s -H /work/hostdir pkg librewolf"

COMMAND="
  while IFS= read -r package; do
    echo \"$BUILD \$package\"
    $BUILD \$package
  done < /work/build-order
"

echo "Running command: $COMMAND"
sh -c "$COMMAND"
